name: operacaomatriz
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  matrix2d: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.0.0

flutter:

  uses-material-design: true
